### ISSUE TITLE
Assertion Error: Coverage Attention Needs to be Set 

### ISSUE THREAD

**Issue by ShyamoliNference** [KaijuML/data-to-text-hierarchical#23]
We have tried training this model following all the instructions on the page, but are running into the following error at the training step. We hope you can give us some tips to fix this error (we have tried different ways to do so, but to no avail):

 Traceback (most recent call last):
  File "train.py", line 6, in <module>
    main()
  File "/content/drive/My Drive/data-to-text-hierarchical-master/onmt/bin/train.py", line 204, in main
    train(opt)
  File "/content/drive/My Drive/data-to-text-hierarchical-master/onmt/bin/train.py", line 88, in train
    single_main(opt, 0)
  File "/content/drive/My Drive/data-to-text-hierarchical-master/onmt/train_single.py", line 98, in main
    opt, device_id, model, fields, optim, model_saver=model_saver)
  File "/content/drive/My Drive/data-to-text-hierarchical-master/onmt/trainer.py", line 35, in build_trainer
    train_loss = onmt.utils.loss.build_loss_compute(model, tgt_field, opt)
  File "/content/drive/My Drive/data-to-text-hierarchical-master/onmt/utils/loss.py", line 30, in build_loss_compute
    assert opt.coverage_attn, "--coverage_attn needs to be set in " \
AssertionError: --coverage_attn needs to be set in order to use --lambda_coverage != 0

Would really appreciate some help with this. Thank you

**Comment by KaijuML** [comment]
Hi,

I think setting `--lambda_coverage 0` will fix this issue. 

If you're using the config file provided at the root of the repo, change [line 71](https://github.com/KaijuML/data-to-text-hierarchical/blob/master/train.cfg#L71) to `lambda_coverage: 0` or simply remove it (default is 0).

I advise to use the [training config file](https://dl.orangedox.com/hierarchical-transformer-checkpoint) from Craig Thomson, where the correct hyperparameter is used (the file is named `train_htransformer.cfg`).

After closing this issue, I'll replace the root config file with this one, so a simple `git pull` should work.

Let me know if this doesn't solve your issue, in which case feel free to re open.
